# Generated by Django 6.0.1 on 2026-01-27 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=50)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=6, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Enter WhatsApp number if contact method is WhatsApp', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
