# Generated by Django 6.0.1 on 2026-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.BooleanField(default=False, help_text="Indicates whether the user's email has been verified for this purchase"),
        ),
    ]
