# Generated by Django 6.0.1 on 2026-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='pending', help_text='Current status of the purchase', max_length=20),
        ),
    ]
