# Generated by Django 6.0.1 on 2026-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='crypto_address',
            field=models.CharField(blank=True, help_text='Wallet address where crypto will be sent', max_length=255, null=True),
        ),
    ]
