# Generated by Django 6.0.1 on 2026-01-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_purchase_crypto_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=50)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('net_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_htg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receive_method', models.CharField(choices=[('western_union', 'Western Union'), ('moncash', 'MonCash')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('moncash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('screenshot', models.ImageField(upload_to='sell_screenshots/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
