# Generated by Django 6.0.1 on 2026-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_selltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
